<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Kosan Kami - Daftar Kamar</title>
    <link rel="stylesheet" href="{{ asset('css/kosan.css') }}">
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo">
                <h1>🏠 Kosan Kami</h1>
            </div>
            <nav class="nav">
                <a href="#home">Beranda</a>
                <a href="#rooms">Kamar</a>
                <a href="#about">Tentang</a>
                <a href="#contact">Kontak</a>
            </nav>
        </div>
    </header>

    <main>
        <!-- Hero Section -->
        <section id="home" class="hero">
            <div class="hero-image">
                <img src="{{ asset('images/aulia-kost.jpg') }}" alt="Gedung Kosan Kami">
                <div class="hero-overlay"></div>
            </div>
            <div class="hero-content">
                <div class="container">
                    <h1 class="hero-title">Selamat Datang di Kosan Kami</h1>
                    <p class="hero-subtitle">16 Kamar nyaman dengan fasilitas lengkap untuk kenyamanan Anda</p>
                    <a href="#rooms" class="hero-btn">Lihat Kamar Tersedia</a>
                </div>
            </div>
        </section>

        <!-- Rooms Section -->
        <section id="rooms" class="rooms-section">
            <div class="container">
                <h2 class="section-title">Daftar Kamar Tersedia</h2>
                <div class="rooms-grid" id="roomsGrid">
                    <!-- Rooms will be generated by JavaScript -->
                </div>
            </div>
        </section>

        <!-- About Section -->
        <section id="about" class="about-section">
            <div class="container">
                <h2 class="section-title">Tentang Kosan Kami</h2>
                <div class="about-content">
                    <p>Kosan Kami menyediakan 16 kamar dengan kualitas yang sama, dilengkapi dengan fasilitas lengkap untuk kenyamanan penghuni. Setiap kamar memiliki standar kualitas tinggi dengan harga terjangkau.</p>
                    
                    <!-- Location Info -->
                    <div class="location-info">
                        <h3>📍 Lokasi Strategis</h3>
                        <p style="margin-bottom: 1.5rem; color: var(--text-light);">Kosan kami berada di lokasi yang strategis dan mudah dijangkau dari berbagai kampus terkemuka di Bandung:</p>
                        <div class="distance-list">
                            <div class="distance-item">
                                <div class="distance-icon">🎓</div>
                                <div class="distance-content">
                                    <h4>Universitas Logistik dan Bisnis</h4>
                                    <p class="distance-text">Jarak: <strong>± 2.5 km</strong> (5-10 menit dengan kendaraan)</p>
                                </div>
                            </div>
                            <div class="distance-item">
                                <div class="distance-icon">🏛️</div>
                                <div class="distance-content">
                                    <h4>Politeknik Negeri Bandung</h4>
                                    <p class="distance-text">Jarak: <strong>± 3.0 km</strong> (7-12 menit dengan kendaraan)</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="facilities">
                        <h3>Fasilitas:</h3>
                        <ul>
                            <li>✓ Kamar mandi dalam</li>
                            <li>✓ WiFi gratis</li>
                            <li>✓ Kasur dan lemari</li>
                            <li>✓ Listrik dan air</li>
                            <li>✓ Keamanan 24 jam</li>
                            <li>✓ Parkir motor</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <!-- Contact Section -->
        <section id="contact" class="contact-section">
            <div class="container">
                <h2 class="section-title">Hubungi Kami</h2>
                <div class="contact-content">
                    <div class="contact-info">
                        <p><strong>Alamat:</strong> Jl. Contoh No. 123, Kota</p>
                        <p><strong>Telepon:</strong> (021) 1234-5678</p>
                        <p><strong>Email:</strong> info@kosankami.com</p>
                        <p><strong>WhatsApp:</strong> +62 812-3456-7890</p>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <!-- Room Modal -->
    <div id="roomModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div id="modalBody">
                <!-- Modal content will be inserted here -->
            </div>
        </div>
    </div>

    <!-- Booking Form Modal -->
    <div id="bookingModal" class="modal">
        <div class="modal-content">
            <span class="close-booking">&times;</span>
            <div id="bookingFormBody">
                <h2>Form Pemesanan Kamar</h2>
                <form id="bookingForm">
                    <div class="form-group">
                        <label for="fullName">Nama Lengkap <span class="required">*</span></label>
                        <input type="text" id="fullName" name="fullName" required placeholder="Masukkan nama lengkap">
                        <span class="error-message" id="fullNameError"></span>
                    </div>
                    <div class="form-group">
                        <label for="email">Email <span class="required">*</span></label>
                        <input type="email" id="email" name="email" required placeholder="contoh@email.com">
                        <span class="error-message" id="emailError"></span>
                    </div>
                    <div class="form-group">
                        <label for="phone">Nomor Telepon <span class="required">*</span></label>
                        <input type="tel" id="phone" name="phone" required placeholder="08xxxxxxxxxx">
                        <span class="error-message" id="phoneError"></span>
                    </div>
                    <input type="hidden" id="selectedRoomNumber" name="roomNumber">
                    <button type="submit" class="modal-btn">Kirim ke WhatsApp</button>
                </form>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p>&copy; {{ date('Y') }} Kosan Kami. All rights reserved.</p>
        </div>
    </footer>

    <script src="{{ asset('js/kosan.js') }}"></script>
</body>
</html>
